name: Versioning

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@4173a1167c90cd065f296f40abc1d35995cf35e7
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
